### ISSUE TITLE
第四題

### ISSUE THREAD

**Issue by YangMengHsuan** [NCU-CSIE-Algorithmics-A-1061/Homework-2#1]
第五組負責

**Comment by YangMengHsuan** [comment]
Given two non-negative function f, g (i.e. f, g : N → R*) such that f≠O(g), f≠θ (g), and f≠Ω(g)

**Comment by YangMengHsuan** [comment]
我們目前想到的兩個函數是
f(n) = sin(n) + 2
g(n) = cos(n) + 2

如此就符合non-negative且f≠O(g), f≠θ (g), and f≠Ω(g)

不知道這樣的想法是否正確

**Comment by pigtwn** [comment]
其實只要1個函數是f(n)=sin(n) + 2就夠了，第二個可以是介於1~3之間的常數也可滿足？
我的想法，供你們參考。

**Comment by YangMengHsuan** [comment]
對欸，謝謝你提供的想法

**Comment by c910335** [comment]
你們可能需要釐清一下這些漸進符號的定義，這裡我以 Big-O 為例

> Let f, g : N → R\*. O(g(n)) denotes the set of functions
> ![f(n):exists c in R^+,exists n0 in N such that all n >= n0, f(n) <= c\*g(n)](http://latex.codecogs.com/gif.latex?f%28n%29%3A%5Cexists%7Bc%7D%5Cin%7BR%5E%2B%7D%2C%5Cexists%7Bn_0%7D%5Cin%7BN%7D%5Cni%5Cforall%7Bn%7D%5Cgeq%7Bn_0%7D%2Cf%28n%29%5Cleq%7Bc%7D%5Ccdot%7Bg%28n%29%7D)

上面那行好像很難懂的數學式翻譯成中文大致上是這樣子的：
存在正實數 c 及正整數 n<sub>0</sub> 使得對於所有的 n ≥ n<sub>0</sub>，有 f(n) ≤ c⋅g(n)

也就是說，如果我們想要確認 f(n) 是不是屬於 O(g(n))，只需找到能夠滿足後面條件的 c 及 n<sub>0</sub> 即可。

於是乎，當 c = 3, n<sub>0</sub> = 1 時，sin(n) + 2 ≤ 3(cos(n) + 2) 恆成立
⇒ sin(n) + 2 = O(cos(n) + 2)

實際上，你們提出的兩個函數並不是三種漸進符號都不成立，而是三者都成立。

**Comment by YangMengHsuan** [comment]
那我們想說
f(n) = |sin(n)|
g(n) = |cos(n)|

這樣是不是就可以了呢

**Comment by YangMengHsuan** [comment]
[HW2_第四題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1349155/HW2_.pptx)

**Comment by c910335** [comment]
@YangMengHsuan 請至 #9 確認 p4.md
