### ISSUE TITLE
第一題

### ISSUE THREAD

**Issue by johnnylin110** [NCU-CSIE-Algorithmics-A-1061/Homework-2#2]
第12組負責

**Comment by johnnylin110** [comment]
假設S集合沒有sort , 可以用merge sort 排序法 O(nlogn)時間，再用下面的演算法找出是否有兩元素相加等於X。 從頭跟尾分別給一個指標，假如＞ｘ就把尾巴往前移，＜Ｘ就把頭往後移，這樣的時間是線性時間O(n)。 因此實作出O(nlogn)的演算法。
假若S集合已被sort過，一樣跑下面的演算法，會在線性時間內O(n)完成。
1 i ← 1, j ← n
2 while i ≤ j do
3 if S[i] +S[ j] = x then
4 return true
5 if S[i] +S[ j] < x then
6 i ← i+1
7 else
8 j ← j −1
9 return false

**Comment by luluiscute** [comment]
[第一題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1348379/default.pptx)

**Comment by c910335** [comment]
> 2 while i ≤ j do

這看起來有可能會跑到 i == j 的情形，
但一個數兩倍等於 x 顯然不是我們要的答案。

**Comment by c910335** [comment]
哪幾行是在 while 迴圈裡呢？
常見的寫法有 do ... end、{ ... }、縮排等。
看起來你們喜歡的是第一種，
不過 end 似乎不見了？

**Comment by c910335** [comment]
建議二、三步交換順序

- Step2: 若已排好則跳過此步驟，否則排序。
- Step3: 略

**Comment by johnnylin110** [comment]
1 i ← 1, j ← n 
2 while i < j do 　　　　　　　
3 	if S[i] +S[ j] = x then 
4 		return true 
5 	if S[i] +S[ j] < x then 
6 		i ← i+1 
7 	else 
8 		j ← j −1 
9	end if
10 return false

已更改code 謝謝 ppt 等等會傳送!

**Comment by johnnylin110** [comment]
![image](https://user-images.githubusercontent.com/32289010/31090435-2fa7994c-a7da-11e7-8a3a-40b9db05a99c.png)

**Comment by johnnylin110** [comment]
等等會補上PPT 謝謝!

**Comment by johnnylin110** [comment]
![image](https://user-images.githubusercontent.com/32289010/31090595-b176f508-a7da-11e7-9f0a-7791445dea81.png)

**Comment by luluiscute** [comment]
[第一題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1349770/default.pptx)

**Comment by c910335** [comment]
我說你的 `return false` 放在迴圈裡面，
那豈不是頭尾加起來錯了的話就失敗了。

**Comment by johnnylin110** [comment]
[第一題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1350938/default.pptx)

**Comment by johnnylin110** [comment]
已修改 謝謝!
![image](https://user-images.githubusercontent.com/32289010/31107161-0a27af10-a823-11e7-85b7-6cfc74d32e15.png)

**Comment by johnnylin110** [comment]
[第一題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1350953/default.pptx)

**Comment by johnnylin110** [comment]
![image](https://user-images.githubusercontent.com/32289010/31107292-0827910c-a824-11e7-984f-9fb591d05db7.png)

**Comment by johnnylin110** [comment]
這是最終版本~~謝謝ˊ

**Comment by c910335** [comment]
@johnnylin110 @luluiscute 
請到 #10 確認 p1.md
