### ISSUE TITLE
第三題

### ISSUE THREAD

**Issue by dining0214** [NCU-CSIE-Algorithmics-A-1061/Homework-2#4]
Problem 3-2: Relative asymptotic growths
Indicate, for each pair of expressions (A, B) in the table below, whether A is O, o, Ω, ω, or Θ of B. Assume that k ≥ 1, ε > 0, and c > 1 are constants. Your answer should be in the form of the table with "yes" or "no" written in each box.

|    A    |    B    |    O    |    o    |    Ω    |    ω    |    Θ    |
|  ------ |  ------ |  ------ |  -----  |  -----  |  -----  |  -----  |
|(log⁡n)^k |   n^ε   |   yes   |   yes   |    no   |    no   |    no   |
|   n^k   |   c^n   |   yes   |   yes   |    no   |    no   |    no   |
|   √n    |n^(sin n)|    no   |    no   |    no   |    no   |    no   |
|   2^n   | 2^(n/2) |    no   |    no   |   yes   |   yes   |    no   |
|n^(log c)|c^(ln n) |    no   |    no   |   yes   |   yes   |    no   |
| log(n!) |log(n^n) |   yes   |    no   |   yes   |    no   |   yes   |

**Comment by dining0214** [comment]
[Uploading AlgorithmHw2Problem3_第八組.pptx…]

**Comment by dining0214** [comment]
[AlgorithmHw2Problem3_第八組.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1349060/AlgorithmHw2Problem3_.pptx)

**Comment by dining0214** [comment]
第八組負責

**Comment by c910335** [comment]
- (b) ![log(n^k)<log(c^n)=>n^k<c^n](http://latex.codecogs.com/gif.latex?%5Clog%7Bn%5Ek%7D%3C%5Clog%7Bc%5En%7D%5CRightarrow%20n%5Ek%3Cc%5En)，這兩句好像是在表示不管 c、n、k 是多少，前者都會小於後者。
- (e) 注意 log 和 ln 的底是不一樣的。
- (f) ![log(1)+..+log(k)](http://latex.codecogs.com/gif.latex?%5CSigma_%7Bk%3D1%7D%5E%7Bn%7Dlog%28k%29) 是如何突然屬於 Θ(nlogn) 的？
- (f) 雖然斯特靈公式很強大，但是代進去之後總是還得有些計算才能得到 Θ(nlogn) 吧。

**Comment by samuel920119920119samuel** [comment]
f. (1)
![sandwich](https://user-images.githubusercontent.com/17474822/31107326-466dc3dc-a824-11e7-9470-c7f59fa71edf.png)
[https://math.stackexchange.com/questions/376988/limit-of-frac-lognn-logn-as-n-to-infty](url)

**Comment by c910335** [comment]
演習課修正的內容更新一下吧

**Comment by dining0214** [comment]
[AlgorithmHw2Problem3RevisedVer._第八組.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1354761/AlgorithmHw2Problem3RevisedVer._.pptx)

**Comment by c910335** [comment]
(e) 為什麼要比 log(n) 和 ln(n)？比較 log(c) 和 ln(c) 不是比較簡單直覺嗎？

**Comment by c910335** [comment]
回應一下吧

**Comment by dining0214** [comment]
喔喔 助教抱歉，那個時候想說兩種比較感覺沒什麼差?
當初想說兩種比較方式就只是兩個數字對掉而已
那我再把PPT改成用 log(c) 和 ln(c)比較好了XD

**Comment by dining0214** [comment]
[AlgorithmHw2Problem3RevisedVer01._.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1385279/AlgorithmHw2Problem3RevisedVer01._.pptx)

**Comment by c910335** [comment]
> (b) log(n^k)<log(c^n)=>n^k<c^n，這兩句好像是在表示不管 c、n、k 是多少，前者都會小於後者。

剛剛才發現原來你還沒回應我這個

**Comment by dining0214** [comment]
阿阿阿那個 當k>0、c>1的時候，前者才會小於後者。

**Comment by c910335** [comment]
n = 2, k = 3, c = 2 符合你說的條件吧
可是看起來 3 > 2 呢

**Comment by dining0214** [comment]
可是討論的條件不是都是在於n趨近於無限大嗎?

**Comment by c910335** [comment]
> 可是討論的條件不是都是在於n趨近於無限大嗎?

< 這個符號並沒有這個意思好嗎
不然你覺得發明 O 和 o 的人在想什麼

**Comment by c910335** [comment]
為什麼不回應了

**Comment by dining0214** [comment]
喔喔 抱歉助教我沒注意到你有回，
好的抱歉我沒搞清楚定義
我會修改好投影片再上傳一次

**Comment by dining0214** [comment]
[AlgorithmHw2Problem3RevisedVer01._.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1421296/AlgorithmHw2Problem3RevisedVer01._.pptx)
