### ISSUE TITLE
第五題

### ISSUE THREAD

**Issue by djosix** [NCU-CSIE-Algorithmics-A-1061/Homework-2#5]
第四組
![screen shot 2017-10-02 at 11 10 57 pm](https://user-images.githubusercontent.com/17045050/31084500-2e9dafb2-a75a-11e7-886c-b00e6f871a75.png)

**Comment by djosix** [comment]
第一小題的思路

![screen shot 2017-10-03 at 11 06 54 am](https://user-images.githubusercontent.com/17045050/31108296-0848cdb0-a7be-11e7-8415-db35d0a48acf.png)

**Comment by djosix** [comment]
第二小題思路
We need a function f that looks like this:

![screenshot from 2017-10-03 00-35-42](https://user-images.githubusercontent.com/17045050/31088353-ed65f7e2-a7d2-11e7-81e0-f3983b7f91b5.png)

when f grows faster then 2^2^n then f != O(any function above)
because f = Omega(0), 0 is not in the candidates, we can simply choose

![screenshot from 2017-10-03 00-49-15](https://user-images.githubusercontent.com/17045050/31088882-c53f99ba-a7d4-11e7-90dc-cad3a0901e7d.png)

**Comment by danieldspp** [comment]
[HW_2_Q5.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1350961/HW_2_Q5.pptx)

**Comment by c910335** [comment]
@djosix @danieldspp 
請至 #11 確認 p5.md

**Comment by djosix** [comment]
![31108296-0848cdb0-a7be-11e7-8415-db35d0a48acf](https://user-images.githubusercontent.com/17045050/32822771-c2b320d0-c99f-11e7-8886-6ad4ea97d79d.png)

**Comment by djosix** [comment]
![photo_2017-11-15_20-34-41](https://user-images.githubusercontent.com/17045050/32893644-42ea1a94-cb15-11e7-8d27-0654d632ee6d.jpg)

**Comment by djosix** [comment]
![photo_2017-11-15_20-34-41](https://user-images.githubusercontent.com/17045050/32893693-693d973e-cb15-11e7-9c1e-08b3ee46f478.jpg)
