### ISSUE TITLE
第三題

### ISSUE THREAD

**Issue by samuel920119920119samuel** [NCU-CSIE-Algorithmics-A-1061/Homework-2#6]
[AlgorithmHw2Problem3_第八組.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1348002/AlgorithmHw2Problem3_.pptx)
有些證明不知道有沒有描述清楚
如果有錯或是說明不清的地方麻煩大家跟我們說一下～～～

**Comment by c910335** [comment]
等我看完再 Close 好嗎QQ

**Comment by samuel920119920119samuel** [comment]
沒啦我剛剛以為我隊友還沒發過ＸＤ
他已經在下面發第三題的issue了～～

**Comment by c910335** [comment]
なんと
