### ISSUE TITLE
第六題

### ISSUE THREAD

**Issue by alifyleo** [NCU-CSIE-Algorithmics-A-1061/Homework-2#8]
T(n)=2*T(n^2)+1
let m=log(n), n=2^m
=> T(2^m)=2*T(2^m/2)+1
let S(m)=T(2^m)
=>S(m)=2*S(m/2)+1
by master theorem : a=2, b=2, f(n)=1
S(m)=m^(log 2)=m
=>S(m)=θ(m)
=>T(2^m)=θ(m)
=>T(n)=θ(log n)

**Comment by alifyleo** [comment]
第十九組

**Comment by alifyleo** [comment]
[第六題.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-2/files/1350992/default.pptx)

**Comment by c910335** [comment]
@alifyleo 請至 #12 確認
